repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.4
          - prettier-plugin-tailwindcss@0.2.4
        files: ^src/
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: src/scripts/eslint.sh
        pass_filenames: false
        language: system
        types: [file]
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.81.0"
    hooks:
      - id: terraform_fmt
        files: \.tf$
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        name: terraform-docs-main
        args: ["markdown", "table", "--output-file", "TERRAFORM_DOCS.md", "./infra"]
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        name: terraform-docs-redirect
        args: ["markdown", "table", "--output-file", "TERRAFORM_DOCS.md", "./infra/redirect"]
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        name: terraform-docs-site-static
        args: ["markdown", "table", "--output-file", "TERRAFORM_DOCS.md", "./infra/site_static"]