repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.4
          - prettier-plugin-tailwindcss@0.2.4
        files: ^v3/
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: v3/scripts/eslint.sh
        pass_filenames: false
        language: system
        types: [file]
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.81.0"
    hooks:
      - id: terraform_fmt