/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: _INSTICT_ (https://sketchfab.com/_INSTICT_)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mona-fbx-with-textures-cd55004dcab14b32b702c197213b297a
title: Mona fbx with textures
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mona({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/mona/scene-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={0.01} position={[1,0,1]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh geometry={nodes.Object_167.geometry} material={materials.material} skeleton={nodes.Object_167.skeleton} />
            <skinnedMesh geometry={nodes.Object_168.geometry} material={materials.material_1} skeleton={nodes.Object_168.skeleton} />
            <skinnedMesh geometry={nodes.Object_169.geometry} material={materials.material_2} skeleton={nodes.Object_169.skeleton} />
            <skinnedMesh geometry={nodes.Object_170.geometry} material={materials.material_3} skeleton={nodes.Object_170.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mona/scene-transformed.glb')
