/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: zixisun02 (https://sketchfab.com/zixisun51)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/shiba-faef9fe5ace445e7b2989d1c1ece361c
title: Shiba
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const modelDir = '/models/shibadog/scene-transformed.glb'

export default function ShibaDog({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(modelDir)
  return (
    <group ref={group} {...props} 
      dispose={null}
      position={[0, 0.2, -1]}
      scale={0.2}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Group18985_default_0.geometry} material={materials['default']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Box002_default_0.geometry} material={materials['default']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Object001_default_0.geometry} material={materials['default']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(modelDir)
