import { DEFAULT_LOCALE } from "@/shared/i18n/settings";
import React, { ReactNode } from "react";
import "./global.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    params,
}: {
    children: ReactNode;
    params: { locale: string };
}) {
    return (
        <React.StrictMode>
            <html lang={params?.locale ?? DEFAULT_LOCALE}>
                <body>
                    <main className=" max-w-screen min-h-screen p-6 md:p-24">
                        {children}
                    </main>
                </body>
            </html>
        </React.StrictMode>
    );
}
