/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Armored Interactive (https://sketchfab.com/ychiang6)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/takodachi-rigged-hololive-fdc37694dcd24bb18184b5ed69fd760a
title: Takodachi_Rigged_Hololive
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { playAnimationsIndefinitely, setCursorPointerOnHover } from '../../utils/utils'
import { playAnimationsOnClick, useHover } from '../../utils/hooks'
import { AnimationMixer } from 'three'
import { LoopOnce } from 'three'
import { Vector3 } from 'three'
import { useFrame } from '@react-three/fiber'


let position = new Vector3(0, 0.5, 9)

export default function Jelly({ ...props }) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/jelly/scene-transformed.glb')
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        playAnimationsIndefinitely([actions.Hop])
    }, [])
    
    const onClickHandler = () => {
        // https://github.com/mrdoob/three.js/blob/master/examples/webgl_animation_skinning_blending.html
        const startAction = actions.Hop;
        const endAction = actions.Stretch;

        endAction.enabled = true;
        endAction.setEffectiveTimeScale(1);
        endAction.setEffectiveWeight(1);
        endAction.setDuration(1.5)
        endAction.setLoop(LoopOnce)
        endAction.time = 0;
        endAction.play()

        // startAction.crossFadeTo(endAction, duration, true);
        const mixer = endAction.getMixer()
        mixer.addEventListener('finished', (event) => {
            mixer.removeEventListener('finished');
            if (event.action === endAction) {
                playAnimationsIndefinitely([startAction])
            }
        });
    }

    const [hover, overHandler, outHandler] = useHover()
    setCursorPointerOnHover(hover)

    useFrame(() => {
        position.x += 0.01
    })

    return (
        <group ref={group} {...props} dispose={null}
            scale={0.02}
            position={position}
            rotation={[0, -Math.PI/2, 0]}
            onClick={onClickHandler}
            onPointerOver={overHandler}
            onPointerOut={outHandler}
        >
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="5fd58d755a0f49559fe8103690da3831fbx" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="Object_2">
                            <group name="RootNode">
                                {/* <group name="Simple">
                                    <group name="Object_5">
                                        <primitive object={nodes._rootJoint} />
                                        <group name="Object_7" />
                                        <group name="Tako_Body_SetUp_01" />
                                        <group name="All_Ctrl_1" position={[192, -14.9, 0]}>
                                            <group name="Halo_Ctrl_1" position={[0, 58.26, 0]} />
                                            <group name="Ear_R_Ctrl_1" position={[15.67, 46.13, -5.05]} />
                                            <group name="Ear_L_Ctrl_1" position={[-15.67, 46.13, -5.05]} />
                                            <group name="Body_Ctrl_1" position={[0, 20.93, 0]}>
                                                <group name="group5_1" position={[-9.78, -11.26, 22.62]} rotation={[-0.91, -0.38, -1.85]}>
                                                    <group name="Leg_L_Ctrl_1_1" />
                                                </group>
                                                <group name="group6_1" position={[-21.65, -11.14, 9.55]} rotation={[-1.29, -0.64, -2.7]}>
                                                    <group name="Leg_L_Ctrl_2_1" />
                                                </group>
                                                <group name="group7_1" position={[-22.61, -11.26, -9.78]} rotation={[-1.87, -0.72, 2.68]}>
                                                    <group name="Leg_L_Ctrl_3_1" />
                                                </group>
                                                <group name="group8_1" position={[-9.54, -11.14, -21.65]} rotation={[-2.31, -0.21, 1.82]}>
                                                    <group name="Leg_L_Ctrl_4_1" />
                                                </group>
                                                <group name="group9_1" position={[9.78, -11.26, 22.62]} rotation={[2.24, -0.38, -1.85]}>
                                                    <group name="Leg_R_Ctrl_1_1" />
                                                </group>
                                                <group name="group10_1" position={[21.65, -11.14, 9.55]} rotation={[1.85, -0.64, -2.7]}>
                                                    <group name="Leg_R_Ctrl_2_1" />
                                                </group>
                                                <group name="group11_1" position={[22.61, -11.26, -9.78]} rotation={[1.27, -0.72, 2.68]}>
                                                    <group name="Leg_R_Ctrl_3_1" />
                                                </group>
                                                <group name="group12_1" position={[9.54, -11.14, -21.65]} rotation={[0.84, -0.21, 1.82]}>
                                                    <group name="Leg_R_Ctrl_4_1" />
                                                </group>
                                            </group>
                                        </group>
                                        <group name="All_LCR_1" position={[192, 15.33, 0]} rotation={[-0.51, 1.57, 2.09]}>
                                            <group name="Halo_LCR_1" position={[28.29, 0.4, 0.03]} rotation={[-0.03, 0, 0.01]} />
                                            <group name="Ear_R_LCR_1" position={[15.88, -5.1, 15.67]} rotation={[-1.42, 0, 1.72]} />
                                            <group name="Ear_L_LCR_1" position={[15.9, -5.08, -15.67]} rotation={[1.42, 0, -1.42]} />
                                            <group name="Body_LCR_1" position={[-9.3, 0.02, 0]} rotation={[3.13, 0, -3.13]}>
                                                <group name="Leg_L_LCR_1_1" position={[11.52, 22.66, 9.38]} rotation={[-1.02, -0.81, 0.15]} />
                                                <group name="Leg_L_LCR_2_1" position={[11.33, 9.79, 21.45]} rotation={[-0.38, -0.87, -0.01]} />
                                                <group name="Leg_L_LCR_3_1" position={[11.27, -9.53, 22.72]} rotation={[0.3, -0.81, -0.04]} />
                                                <group name="Leg_L_LCR_4_1" position={[10.98, -21.6, 9.84]} rotation={[1.23, -0.82, 0.01]} />
                                                <group name="Leg_R_LCR_1_1" position={[11.43, 22.36, -10.19]} rotation={[0.99, 0.82, -3]} />
                                                <group name="Leg_R_LCR_2_1" position={[11.14, 9.1, -21.85]} rotation={[0.35, 0.88, 3.13]} />
                                                <group name="Leg_R_LCR_3_1" position={[11.07, -10.24, -22.5]} rotation={[-0.33, 0.81, 3.1]} />
                                                <group name="Leg_R_LCR_4_1" position={[10.89, -21.9, -9.25]} rotation={[-1.27, 0.82, -3.12]} />
                                            </group>
                                        </group>
                                        <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.lambert4} skeleton={nodes.Object_8.skeleton} />
                                        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Body} skeleton={nodes.Object_9.skeleton} />
                                        <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material} skeleton={nodes.Object_10.skeleton} />
                                    </group>
                                </group> */}
                                <group name="Subbed">
                                    <group name="Object_71">
                                        <group name="All_Ctrl" position={[0, -14.9, 0]}>
                                            <group name="Halo_Ctrl" position={[0, 58.26, 0]} />
                                            <group name="Ear_R_Ctrl" position={[15.67, 46.13, -5.05]} />
                                            <group name="Ear_L_Ctrl" position={[-15.67, 46.13, -5.05]} />
                                            <group name="Body_Ctrl" position={[0, 20.93, 0]}>
                                                <group name="group5" position={[-9.78, -11.26, 22.62]} rotation={[-0.91, -0.38, -1.85]}>
                                                    <group name="Leg_L_Ctrl_1" />
                                                </group>
                                                <group name="group6" position={[-21.65, -11.14, 9.55]} rotation={[-1.29, -0.64, -2.7]}>
                                                    <group name="Leg_L_Ctrl_2" />
                                                </group>
                                                <group name="group7" position={[-22.61, -11.26, -9.78]} rotation={[-1.87, -0.72, 2.68]}>
                                                    <group name="Leg_L_Ctrl_3" />
                                                </group>
                                                <group name="group8" position={[-9.54, -11.14, -21.65]} rotation={[-2.31, -0.21, 1.82]}>
                                                    <group name="Leg_L_Ctrl_4" />
                                                </group>
                                                <group name="group9" position={[9.78, -11.26, 22.62]} rotation={[2.24, -0.38, -1.85]}>
                                                    <group name="Leg_R_Ctrl_1" />
                                                </group>
                                                <group name="group10" position={[21.65, -11.14, 9.55]} rotation={[1.85, -0.64, -2.7]}>
                                                    <group name="Leg_R_Ctrl_2" />
                                                </group>
                                                <group name="group11" position={[22.61, -11.26, -9.78]} rotation={[1.27, -0.72, 2.68]}>
                                                    <group name="Leg_R_Ctrl_3" />
                                                </group>
                                                <group name="group12" position={[9.54, -11.14, -21.65]} rotation={[0.84, -0.21, 1.82]}>
                                                    <group name="Leg_R_Ctrl_4" />
                                                </group>
                                            </group>
                                        </group>
                                        <group name="All_LCR" position={[0, 15.33, 0]} rotation={[-0.51, 1.57, 2.09]}>
                                            <group name="Halo_LCR" position={[28.29, 0.4, 0.03]} rotation={[-0.03, 0, 0.01]} />
                                            <group name="Ear_R_LCR" position={[15.88, -5.1, 15.67]} rotation={[-1.42, 0, 1.72]} />
                                            <group name="Ear_L_LCR" position={[15.9, -5.08, -15.67]} rotation={[1.42, 0, -1.42]} />
                                            <group name="Body_LCR" position={[-9.3, 0.02, 0]} rotation={[3.13, 0, -3.13]}>
                                                <group name="Leg_L_LCR_1" position={[11.52, 22.66, 9.38]} rotation={[-1.02, -0.81, 0.15]} />
                                                <group name="Leg_L_LCR_2" position={[11.33, 9.79, 21.45]} rotation={[-0.38, -0.87, -0.01]} />
                                                <group name="Leg_L_LCR_3" position={[11.27, -9.53, 22.72]} rotation={[0.3, -0.81, -0.04]} />
                                                <group name="Leg_L_LCR_4" position={[10.98, -21.6, 9.84]} rotation={[1.23, -0.82, 0.01]} />
                                                <group name="Leg_R_LCR_1" position={[11.43, 22.36, -10.19]} rotation={[0.99, 0.82, -3]} />
                                                <group name="Leg_R_LCR_2" position={[11.14, 9.1, -21.85]} rotation={[0.35, 0.88, 3.13]} />
                                                <group name="Leg_R_LCR_3" position={[11.07, -10.24, -22.5]} rotation={[-0.33, 0.81, 3.1]} />
                                                <group name="Leg_R_LCR_4" position={[10.89, -21.9, -9.25]} rotation={[-1.27, 0.82, -3.12]} />
                                            </group>
                                        </group>
                                        <primitive object={nodes._rootJoint_1} />
                                        <group name="Object_73" />
                                        <group name="Tako_Body_SetUp_01_1" />
                                        <skinnedMesh castShadow receiveShadow name="Object_74" geometry={nodes.Object_74.geometry} material={materials.lambert4} skeleton={nodes.Object_74.skeleton} />
                                        <skinnedMesh castShadow receiveShadow name="Object_75" geometry={nodes.Object_75.geometry} material={materials.Body} skeleton={nodes.Object_75.skeleton} />
                                        <skinnedMesh castShadow receiveShadow name="Object_76" geometry={nodes.Object_76.geometry} material={materials.material} skeleton={nodes.Object_76.skeleton} />
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/jelly/scene-transformed.glb')
