import Theme from "@/components/theme/Theme";
import { DEFAULT_LOCALE } from "@/shared/i18n/settings";
import React, { ReactNode } from "react";
import "./global.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    params,
}: {
    children: ReactNode;
    params: { locale: string };
}) {
    return (
        <html lang={params?.locale ?? DEFAULT_LOCALE}>
            <body>
                <Theme>{children}</Theme>
            </body>
        </html>
    );
}
