import './globals.css'
import { notFound } from 'next/navigation';
import Theme from '@/components/theme/Theme';
import { LOCALES } from '@/shared/i18n/settings';



export async function generateStatticParams() {
  return LOCALES.map(locale => {{ locale }});
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: { locale: string }
}) {


  return (
    <html lang={params.locale}>
      <body>
        <Theme>
          {children}
        </Theme>
      </body>
    </html>
  )
}
